// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfUuy0IUfeN7CztzHDVROFjsCFlZpWKU',
    appId: '1:950383333047:web:59129abcbcf6f7f74c8732',
    messagingSenderId: '950383333047',
    projectId: 'clubhub-7dbbd',
    authDomain: 'clubhub-7dbbd.firebaseapp.com',
    storageBucket: 'clubhub-7dbbd.appspot.com',
    measurementId: 'G-VBTTH3DY3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD131WT82inEP2gAL2HzS0-uaJ6YzxwSBA',
    appId: '1:950383333047:android:7a77b5c6a9ac47334c8732',
    messagingSenderId: '950383333047',
    projectId: 'clubhub-7dbbd',
    storageBucket: 'clubhub-7dbbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgfaqRfY0EIAVz5xhC2O5v7ZkMhuly-Xs',
    appId: '1:950383333047:ios:90fdd095f210dcd44c8732',
    messagingSenderId: '950383333047',
    projectId: 'clubhub-7dbbd',
    storageBucket: 'clubhub-7dbbd.appspot.com',
    iosBundleId: 'com.example.clubHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgfaqRfY0EIAVz5xhC2O5v7ZkMhuly-Xs',
    appId: '1:950383333047:ios:3a6b0998747f41fe4c8732',
    messagingSenderId: '950383333047',
    projectId: 'clubhub-7dbbd',
    storageBucket: 'clubhub-7dbbd.appspot.com',
    iosBundleId: 'com.example.clubHub.RunnerTests',
  );
}
