// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy10BLvyYZs8aZhpscQjinCIENrE_z50k',
    appId: '1:734536051737:web:a71ee0348981882eebce88',
    messagingSenderId: '734536051737',
    projectId: 'clubhub-7efc4',
    authDomain: 'clubhub-7efc4.firebaseapp.com',
    storageBucket: 'clubhub-7efc4.appspot.com',
    measurementId: 'G-74DGN6FR0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsljdMxsxRqK-sP5U57j0MoRn4TmSKRv0',
    appId: '1:734536051737:android:b8ac601fb52ce01debce88',
    messagingSenderId: '734536051737',
    projectId: 'clubhub-7efc4',
    storageBucket: 'clubhub-7efc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7gdfoom03dXWgAVzWCszcHKm6vQpNP2Y',
    appId: '1:734536051737:ios:472d021da4274be9ebce88',
    messagingSenderId: '734536051737',
    projectId: 'clubhub-7efc4',
    storageBucket: 'clubhub-7efc4.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7gdfoom03dXWgAVzWCszcHKm6vQpNP2Y',
    appId: '1:734536051737:ios:212039d9b2bb059febce88',
    messagingSenderId: '734536051737',
    projectId: 'clubhub-7efc4',
    storageBucket: 'clubhub-7efc4.appspot.com',
    iosBundleId: 'com.example.newproject.RunnerTests',
  );
}
